services:
    # TIER 1: Frontend
    frontend:
        build: ./frontend
        ports:
        - "3000:3000"
        volumes:
        # Map your local folder to the container so you can edit code live
        - ./frontend:/app
        - /app/node_modules
        environment:
        # Tell Next.js where AWS is
        - AWS_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
        - AWS_ENDPOINT_URL=http://localstack:4566
        depends_on:
        - localstack

  # TIER 2 & 3: Local AWS (Backend + DB)
    localstack:
        image: localstack/localstack
        ports:
        - "4566:4566"
        environment:
        - SERVICES=s3,dynamodb,lambda,apigateway,cloudformation,sts,iam
        - DEBUG=1
        - DOCKER_HOST=unix:///var/run/docker.sock
        # CRITICAL: This tells LocalStack "If you see a Lambda pointing to s3://... or a path, look here"
        - LAMBDA_REMOTE_DOCKER=0
        volumes:
        - ./localstack-init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
        # Mount the ENTIRE backend folder so CloudFormation can find "src/"
        - ./backend:/etc/localstack/init/ready.d/backend
        - "/var/run/docker.sock:/var/run/docker.sock"